taichi/ci-yarn-upgrade

yarn.lock

| [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn#readme) | [4.0.2](https://github.com/IndigoUnited/node-cross-spawn/tree/4.0.2) | [5.0.0](https://github.com/IndigoUnited/node-cross-spawn/compare/4.0.2...5.0.0) | * |
| [git-url-parse](https://github.com/IonicaBizau/git-url-parse) | 6.0.7...6.1.0 | 6.1.0 | * |
| [github](https://github.com/mikedeboer/node-github) | [5.3.3](https://github.com/mikedeboer/node-github/tree/v5.3.3) | [6.0.1](https://github.com/mikedeboer/node-github/compare/v5.3.3...v6.0.1) | * |

update dependencies at 20161104042957

---

yarn.lock

| [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn#readme) | [4.0.2](https://github.com/IndigoUnited/node-cross-spawn/tree/4.0.2) | [5.0.1](https://github.com/IndigoUnited/node-cross-spawn/compare/4.0.2...5.0.1) | * |   |
| [eslint](http://eslint.org) | [3.9.1...3.10.2](https://github.com/eslint/eslint/compare/v3.9.1...v3.10.2) | [3.10.2](https://github.com/eslint/eslint/compare/v3.9.1...v3.10.2) |   | * |
| [github](https://github.com/mikedeboer/node-github) | [5.3.3](https://github.com/mikedeboer/node-github/tree/v5.3.3) | [6.0.4](https://github.com/mikedeboer/node-github/compare/v5.3.3...v6.0.4) | * |   |
| [lodash](https://lodash.com/) | …

update dependencies at 20161117043014

---

yarn.lock

| Name | Updating | Latest | devDependencies |
| [eslint](http://eslint.org) | [3.12.0...3.12.1](https://github.com/eslint/eslint/compare/v3.12.0...v3.12.1) | [3.12.1](https://github.com/eslint/eslint/compare/v3.12.0...v3.12.1) | * |

update dependencies at 20161214020327

---

src/upgrade-request.js
test/upgrade-request.test.js

ci-yarn-upgrade do not working from yarn v1.8.0.
@taichi Please check for https://github.com/yarnpkg/yarn/pull/2022.
`$ yarn outdated --json` command do not outputs footer from yarn v1.8.0.
```
$ yarn --version
0.17.9
$ yarn outdated --json
{"type":"table","data":{"head":["Package","Current","Wanted","Latest","Package Type"],"body":[["eslint-config-airbnb","13.0.0","13.0.0","14.1.0","devDependencies"],["eslint-plugin-jsx-a11y","2.2.3","2.2.3","4.0.0","devDependencies"],["eslint-plugin-node","2.1.4","2.1.4","4.0.1","devDependencies"],["eslint-plugin-react","6.9.0","6.10.0","6.10.0","devDependencies"],["serverless","1.6.1","1.7.0","1.7.0","devDependencies"]]}}
{"type":"finished","data":2466}
$ ci-yarn-upgrade--execute -n tsub -e tsubasatakayama511@gmail.com -t xxxxx -v
> BEGIN yarnpkg …
```

Fix a bug always outputs "dependecies are not up to date"

---

yarn.lock

| [ava](https://ava.li) | 0.22.0 | 0.24.0 |   | * |
| [babel-preset-env](https://babeljs.io/) | 1.6.0...1.6.1 | 1.6.1 |   | * |
| [commander](https://github.com/tj/commander.js#readme) | 2.11.0...2.12.2 | 2.12.2 | * |   |
| [cross-env](https://github.com/kentcdodds/cross-env#readme) | 5.0.5...5.1.1 | 5.1.1 |   | * |
| [eslint](https://eslint.org) | 4.8.0...4.12.1 | 4.12.1 |   | * |
| [github](https://github.com/mikedeboer/node-github) | 11.0.0 | 12.1.0 | * |   |
| [moment](http://momentjs.com) | 2.18.1...2.19.3 | 2.19.3 | * |   |

update dependencies at 20171206020114

---

yarn.lock

| [ava](https://ava.li) | 0.22.0 | 0.25.0 |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | 1.7.0 | 2.0.2 |   | * |
| [commander](https://github.com/tj/commander.js#readme) | 2.12.2...2.14.1 | 2.14.1 | * |   |
| [cross-env](https://github.com/kentcdodds/cross-env#readme) | 5.1.1...5.1.3 | 5.1.3 |   | * |
| [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn#readme) | 5.1.0 | 6.0.4 | * |   |
| [eslint](https://eslint.org) | 4.12.1...4.18.1 | 4.18.1 |   | * |
| [git-url-parse](https://github.com/IonicaBizau/git-url-parse) | 7.0.1...7.2.0 | 8.1.0 | * |   |
| [github](https://github.com/mikedeboer/node-github) | 11.0.0 | 13.1.0 | * |   |
| [lodash](https://lodash.com/) | …

update dependencies at 20180221020113

---

yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [14.0.9](https://github.com/octokit/rest.js/tree/v14.0.9) | [15.2.2](https://github.com/octokit/rest.js/compare/v14.0.9...v15.2.2) | * |   |
| [ava](https://ava.li) | [0.22.0](https://github.com/avajs/ava/tree/v0.22.0) | [0.25.0](https://github.com/avajs/ava/compare/v0.22.0...v0.25.0) |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | [1.7.0](https://github.com/paulmillr/chokidar/tree/1.7.0) | [2.0.2](https://github.com/paulmillr/chokidar/compare/1.7.0...2.0.2) |   | * |
| [colors](https://github.com/Marak/colors.js) | [1.1.2...1.2.1](https://github.com/Marak/colors.js/compare/v1.1.2...v1.2.1) | …

update dependencies at 20180314020133

---

yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [14.0.9](https://github.com/octokit/rest.js/tree/v14.0.9) | [15.2.6](https://github.com/octokit/rest.js/compare/v14.0.9...v15.2.6) | * |   |
| [ava](https://ava.li) | [0.22.0](https://github.com/avajs/ava/tree/v0.22.0) | [0.25.0](https://github.com/avajs/ava/compare/v0.22.0...v0.25.0) |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | [1.7.0](https://github.com/paulmillr/chokidar/tree/1.7.0) | [2.0.3](https://github.com/paulmillr/chokidar/compare/1.7.0...2.0.3) |   | * |
| [commander](https://github.com/tj/commander.js#readme) | [2.15.0...2.15.1](https://github.com/tj/commander.js/compare/v2.15.0...v2.15.1) | …

update dependencies at 20180418020108

---

package.json
src/compare.js
yarn.lock

see. 
* jamestalmage/cli-table2#48
* jamestalmage/cli-table2#43

security fix

---

yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [15.4.0...15.5.1](https://github.com/octokit/rest.js/compare/v15.4.0...v15.5.1) | [15.5.1](https://github.com/octokit/rest.js/compare/v15.4.0...v15.5.1) | * |   |
| [babel-preset-env](https://babeljs.io/) | [1.6.1...1.7.0](https://github.com/babel/babel-preset-env/compare/v1.6.1...v1.7.0) | [1.7.0](https://github.com/babel/babel-preset-env/compare/v1.6.1...v1.7.0) |   | * |
| [colors](https://github.com/Marak/colors.js) | [1.2.4...1.2.5](https://github.com/Marak/colors.js/compare/v1.2.4...v1.2.5) | [1.2.5](https://github.com/Marak/colors.js/compare/v1.2.4...v1.2.5) | * |   |
Powered by …

update dependencies at 20180516034820

---

yarn.lock

| [colors](https://github.com/Marak/colors.js) | [1.2.5...1.3.0](https://github.com/Marak/colors.js/compare/v1.2.5...v1.3.0) | [1.3.0](https://github.com/Marak/colors.js/compare/v1.2.5...v1.3.0) | * |   |
| [cross-env](https://github.com/kentcdodds/cross-env#readme) | [5.1.5...5.1.6](https://github.com/kentcdodds/cross-env/compare/v5.1.5...v5.1.6) | [5.1.6](https://github.com/kentcdodds/cross-env/compare/v5.1.5...v5.1.6) |   | * |

update dependencies at 20180523040204

---

src/upgrade-request.js
test/upgrade-request.test.js
yarn.lock

Add package json to pull request changes when latest

---

package.json
yarn.lock

| [colors](https://github.com/Marak/colors.js) | [1.3.0...1.3.1](https://github.com/Marak/colors.js/compare/v1.3.0...v1.3.1) | [1.3.1](https://github.com/Marak/colors.js/compare/v1.3.0...v1.3.1) | * |   |
| [eslint](https://eslint.org) | [4.19.1](https://github.com/eslint/eslint/tree/v4.19.1) | [5.4.0](https://github.com/eslint/eslint/compare/v4.19.1...v5.4.0) |   | * |
| [git-url-parse](https://github.com/IonicaBizau/git-url-parse) | [9.0.1](https://github.com/IonicaBizau/git-url-parse/tree/9.0.1) | [10.0.1](https://github.com/IonicaBizau/git-url-parse/compare/9.0.1...10.0.1) | * |   |

update dependencies at 20180822010032

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [15.10.0...15.13.1](https://github.com/octokit/rest.js/compare/v15.10.0...v15.13.1) | [15.13.1](https://github.com/octokit/rest.js/compare/v15.10.0...v15.13.1) | * |   |
| [commander](https://github.com/tj/commander.js#readme) | [2.17.1...2.19.0](https://github.com/tj/commander.js/compare/v2.17.1...v2.19.0) | [2.19.0](https://github.com/tj/commander.js/compare/v2.17.1...v2.19.0) | * |   |
| [eslint](https://eslint.org) | [5.4.0...5.7.0](https://github.com/eslint/eslint/compare/v5.4.0...v5.7.0) | [5.7.0](https://github.com/eslint/eslint/compare/v5.4.0...v5.7.0) |   | * |
| …

update dependencies at 20181017010026

---

package.json
yarn.lock

| [git-url-parse](https://github.com/IonicaBizau/git-url-parse) | [11.0.1...11.1.1](https://github.com/IonicaBizau/git-url-parse/compare/11.0.1...11.1.1) | [11.1.1](https://github.com/IonicaBizau/git-url-parse/compare/11.0.1...11.1.1) | * |

update dependencies at 20181107010027

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.9.0...16.13.1](https://github.com/octokit/rest.js/compare/v16.9.0...v16.13.1) | [16.13.1](https://github.com/octokit/rest.js/compare/v16.9.0...v16.13.1) | * |   |
| [eslint](https://eslint.org) | [5.12.0...5.12.1](https://github.com/eslint/eslint/compare/v5.12.0...v5.12.1) | [5.12.1](https://github.com/eslint/eslint/compare/v5.12.0...v5.12.1) |   | * |
| [moment](http://momentjs.com) | [2.23.0...2.24.0](https://github.com/moment/moment/compare/2.23.0...2.24.0) | [2.24.0](https://github.com/moment/moment/compare/2.23.0...2.24.0) | * |   |

update dependencies at 20190123010026

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.13.1...16.13.4](https://github.com/octokit/rest.js/compare/v16.13.1...v16.13.4) | [16.13.4](https://github.com/octokit/rest.js/compare/v16.13.1...v16.13.4) | * |   |
| [ava](https://ava.li) | [1.1.0...1.2.0](https://github.com/avajs/ava/compare/v1.1.0...v1.2.0) | [1.2.0](https://github.com/avajs/ava/compare/v1.1.0...v1.2.0) |   | * |

update dependencies at 20190130010026

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.13.4...16.15.0](https://github.com/octokit/rest.js/compare/v16.13.4...v16.15.0) | [16.15.0](https://github.com/octokit/rest.js/compare/v16.13.4...v16.15.0) | * |   |
| [ava](https://ava.li) | [1.2.0...1.2.1](https://github.com/avajs/ava/compare/v1.2.0...v1.2.1) | [1.2.1](https://github.com/avajs/ava/compare/v1.2.0...v1.2.1) |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | [2.0.4...2.1.0](https://github.com/paulmillr/chokidar/compare/2.0.4...2.1.0) | [2.1.0](https://github.com/paulmillr/chokidar/compare/2.0.4...2.1.0) |   | * |
| [eslint](https://eslint.org) | …

update dependencies at 20190206010032

---

package.json
yarn.lock

| `@babel/register` | [7.0.0...7.4.0](https://github.com/babel/babel/compare/v7.0.0...v7.4.0) | [7.4.0](https://github.com/babel/babel/compare/v7.0.0...v7.4.0) |   | * |
| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.15.0...16.21.0](https://github.com/octokit/rest.js/compare/v16.15.0...v16.21.0) | [16.21.0](https://github.com/octokit/rest.js/compare/v16.15.0...v16.21.0) | * |   |
| [ava](https://ava.li) | [1.2.1...1.4.1](https://github.com/avajs/ava/compare/v1.2.1...v1.4.1) | [1.4.1](https://github.com/avajs/ava/compare/v1.2.1...v1.4.1) |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | [2.1.0...2.1.5](https://github.com/paulmillr/chokidar/compare/2.1.0...2.1. …

update dependencies at 20190327010033

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.21.0...16.23.2](https://github.com/octokit/rest.js/compare/v16.21.0...v16.23.2) | [16.23.2](https://github.com/octokit/rest.js/compare/v16.21.0...v16.23.2) | * |   |
| [commander](https://github.com/tj/commander.js#readme) | [2.19.0...2.20.0](https://github.com/tj/commander.js/compare/v2.19.0...v2.20.0) | [2.20.0](https://github.com/tj/commander.js/compare/v2.19.0...v2.20.0) | * |   |
| [eslint](https://eslint.org) | [5.15.3...5.16.0](https://github.com/eslint/eslint/compare/v5.15.3...v5.16.0) | [5.16.0](https://github.com/eslint/eslint/compare/v5.15.3...v5.16.0) |   | * |
Powered by …

update dependencies at 20190403010027

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.23.2...16.25.0](https://github.com/octokit/rest.js/compare/v16.23.2...v16.25.0) | [16.25.0](https://github.com/octokit/rest.js/compare/v16.23.2...v16.25.0) | * |

update dependencies at 20190424010029

---

package.json
yarn.lock

| `@babel/register` | [7.4.0...7.4.4](https://github.com/babel/babel/compare/v7.4.0...v7.4.4) | [7.4.4](https://github.com/babel/babel/compare/v7.4.0...v7.4.4) |   | * |
| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.25.0...16.25.3](https://github.com/octokit/rest.js/compare/v16.25.0...v16.25.3) | [16.25.3](https://github.com/octokit/rest.js/compare/v16.25.0...v16.25.3) | * |   |
| [chokidar](https://github.com/paulmillr/chokidar) | [2.1.5](https://github.com/paulmillr/chokidar/tree/2.1.5) | [3.0.0](https://github.com/paulmillr/chokidar/compare/2.1.5...3.0.0) |   | * |

update dependencies at 20190508010030

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.25.3...16.25.5](https://github.com/octokit/rest.js/compare/v16.25.3...v16.25.5) | [16.25.5](https://github.com/octokit/rest.js/compare/v16.25.3...v16.25.5) | * |

update dependencies at 20190515010041

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.25.5...16.27.0](https://github.com/octokit/rest.js/compare/v16.25.5...v16.27.0) | [16.27.0](https://github.com/octokit/rest.js/compare/v16.25.5...v16.27.0) | * |

update dependencies at 20190529010037

---

package.json
yarn.lock

| [@octokit/rest](https://github.com/octokit/rest.js#readme) | [16.27.0...16.28.1](https://github.com/octokit/rest.js/compare/v16.27.0...v16.28.1) | [16.28.1](https://github.com/octokit/rest.js/compare/v16.27.0...v16.28.1) | * |   |
| [ava](https://avajs.dev) | [1.4.1](https://github.com/avajs/ava/tree/v1.4.1) | [2.1.0](https://github.com/avajs/ava/compare/v1.4.1...v2.1.0) |   | * |
| [chokidar](https://github.com/paulmillr/chokidar) | [3.0.0...3.0.1](https://github.com/paulmillr/chokidar/compare/3.0.0...3.0.1) | [3.0.1](https://github.com/paulmillr/chokidar/compare/3.0.0...3.0.1) |   | * |

update dependencies at 20190612010030
